### ISSUE TITLE
Repeated look ups with `PaginatedResult`, issued with the offset value

### ISSUE THREAD

**Issue by atulpatare** [FuelLabs/fuel-indexer#364] opened 2022-11-28 16:49 UTC
I have concerns with this function [here](https://github.com/FuelLabs/fuel-indexer/blob/a5753c425798a787f4d8aec888f16e4a23d567d9/fuel-indexer/src/service.rs#L125)

`To note I have start_block defined to 190875 in my config.yaml and Im running on testnet`

I have added a few logs here(`println`)
```rust
loop {
            println!("Fetching paginated results from {:?}", next_cursor);
            debug!("Fetching paginated results from {:?}", next_cursor);
            // TODO: can we have a "start at height" option?
            let PaginatedResult {
                cursor, results, ..
            } = client
                .blocks(PaginationRequest {
                    cursor: next_cursor.clone(),
                    results: 10,
                    direction: PageDirection::Forward,
                })
                .await
                .expect("Failed to retrieve blocks");

            debug!("Processing {} results", results.len());
            println!("Processing {} results", results.len().to_string());

            let mut block_info = Vec::new();
            for block in results.into_iter().rev() {
                if block.header.height.0 != next_block {
                    next_cursor = Some(next_block.to_string());
                    println!("Skipping the block : {}", block.header.height.0.to_string());

                    continue;
                }
```

The output in console after running is something like this
```
Processing 10 results
Skipping the block : 1
Skipping the block : 2
Skipping the block : 3
Skipping the block : 4
Skipping the block : 5
Skipping the block : 6
Skipping the block : 7
Skipping the block : 8
Skipping the block : 9
Skipping the block : 10
// other stuff
Fetching paginated results from Some("1")
Processing 10 results
Skipping the block : 2
Skipping the block : 3
Skipping the block : 4
Skipping the block : 5
Skipping the block : 6
Skipping the block : 7
Skipping the block : 8
Skipping the block : 9
Skipping the block : 10
Skipping the block : 11
// other stuff
Fetching paginated results from Some("2")
Processing 10 results
Skipping the block : 3
Skipping the block : 4
Skipping the block : 5
Skipping the block : 6
Skipping the block : 7
Skipping the block : 8
Skipping the block : 9
Skipping the block : 10
Skipping the block : 11
Skipping the block : 12
// other stuff
Fetching paginated results from Some("3")
Processing 10 results
Skipping the block : 4
Skipping the block : 5
Skipping the block : 6
Skipping the block : 7
Skipping the block : 8
Skipping the block : 9
Skipping the block : 10
Skipping the block : 11
Skipping the block : 12
Skipping the block : 13
```

You see whats happening. Consider below as loop pass for processing blocks with each containing 10 results
```
## Actual
PASS 1 :  block 1, block 2, block 3 .... block 10
PASS 2 :  block 2, block 3, block 4 .... block 11
PASS 3 :  block 3, block 4, block 5 .... block 12
etc.

## Expected
PASS 1 : block 1, block 2, block 3 .... block 10
PASS 2 : block 11, block 12, block 13 ... block 20
so on.
```

Reason the cursor is supposed to be an offsett for the graphql query [offset](https://github.com/FuelLabs/fuel-indexer/blob/a5753c425798a787f4d8aec888f16e4a23d567d9/fuel-indexer/src/service.rs#L145)
```
The cursor value goes from 1, 2, 3, 4, .. 
It should be 

offset = previous_cursor * result.len
offset = 1 * 10

now it should be 10, 20, 30, 40, 50 ...
```

One other thing, the solution for this [todo](https://github.com/FuelLabs/fuel-indexer/blob/a5753c425798a787f4d8aec888f16e4a23d567d9/fuel-indexer/src/service.rs#L140) can be derived by the use of the `offset` i.e. `cursor` in `PaginationRequest`. If the current block is not the `start_block` then set `cursor` to `Some(start_block)` this way the result with start from the end of offset

**Comment by deekerno** [comment] 2022-11-28 23:07
This is being caused by https://github.com/FuelLabs/fuel-core/issues/795. I'll work on fixing this upstream.

**Comment by ra0x3** [comment] 2022-11-30 14:57
Fixed in https://github.com/FuelLabs/fuel-core/pull/800

**Closed by ra0x3** 2022-11-30 14:57 UTC
Labels: bug, P: High
