### ISSUE TITLE
forc-index --manifest only runs a single indexer even if more are registered

### ISSUE THREAD

**Issue by lostman** [FuelLabs/fuel-indexer#1413] opened 2023-10-14 12:04 UTC
### Description

I noticed that when I have multiple registered indexers and start `fuel-indexer` with `--manifest` option, only that single indexer is started:

```
cargo run -p fuel-indexer -- run --fuel-node-host beta-4.fuel.network --fuel-node-port 80 --replace-indexer --manifest examples/fuel-explorer/fuel-explorer/fuel_explorer.manifest.yaml
```

```
2023-10-14T11:54:33.345220Z  INFO fuel_indexer::commands::run: 117: Using manifest file located at 'examples/fuel-explorer/fuel-explorer/fuel_explorer.manifest.yaml'
2023-10-14T11:54:33.346304Z  INFO fuel_indexer::commands::run: 121: ✨ ✨ GraphQL Playground at: http://localhost:29987/api/playground/fuellabs/explorer
2023-10-14T11:54:33.417216Z  INFO fuel_indexer::service: 405: Resuming Indexer(fuellabs.explorer) from block 99921
2023-10-14T11:54:38.187713Z  INFO fuel_indexer::database: 219: Database loading schema for Indexer(fuellabs.explorer) with Version(bca69dba935a24f511cef34298b2e1e6e8637c29244b208458c3b73ca6088be3).
2023-10-14T11:54:38.228734Z  INFO fuel_indexer::service: 157: Registering Asset(Schema) for Indexer(fuellabs.explorer)
2023-10-14T11:54:38.237473Z  INFO fuel_indexer_postgres: 571: Registered Asset(Schema) with Version(bca69dba935a24f511cef34298b2e1e6e8637c29244b208458c3b73ca6088be3) to Indexer(fuellabs.explorer).
2023-10-14T11:54:38.237546Z  INFO fuel_indexer::service: 157: Registering Asset(Manifest) for Indexer(fuellabs.explorer)
2023-10-14T11:54:38.240872Z  INFO fuel_indexer_postgres: 571: Registered Asset(Manifest) with Version(0c17f3477d8541298918c084753327299846574b1aab013240bc81fb5548a67f) to Indexer(fuellabs.explorer).
2023-10-14T11:54:38.240889Z  INFO fuel_indexer::service: 157: Registering Asset(Wasm) for Indexer(fuellabs.explorer)
2023-10-14T11:54:38.317391Z  INFO fuel_indexer_postgres: 571: Registered Asset(Wasm) with Version(557be6c54530382279ac992699fc0e3bd0b14f12168bf80ae7808c9c62b35553) to Indexer(fuellabs.explorer).
2023-10-14T11:54:38.317461Z  INFO fuel_indexer::service: 174: Registered Indexer(fuellabs.explorer)
2023-10-14T11:54:38.317587Z  INFO fuel_indexer::executor: 106: Indexer(fuellabs.explorer) subscribing to Fuel node at beta-4.fuel.network:80
2023-10-14T11:54:38.318773Z  WARN fuel_indexer::executor: 115: No end_block specified in the manifest. Indexer(fuellabs.explorer) will run forever.
2023-10-14T11:54:38.322771Z  INFO fuel_indexer_lib::utils: 144: Parsed SocketAddr '127.0.0.1:29987' from 'localhost:29987'
```

In contrast, if I simply start `fuel-indexer`, all indexers are started:

```
cargo run -p fuel-indexer -- run --fuel-node-host beta-4.fuel.network --fuel-node-port 80 --replace-indexer
```

```
2023-10-14T12:00:18.503332Z  INFO fuel_indexer::service: 405: Resuming Indexer(mw.some_indexer_3) from block 77081
2023-10-14T12:00:21.048364Z  INFO fuel_indexer::database: 219: Database loading schema for Indexer(mw.some_indexer_3) with Version(780caa2e6464415ff2f96bfc600e6ff4887f206c07d47771ce8646e668aa5c27).
2023-10-14T12:00:21.070687Z  INFO fuel_indexer::service: 205: Registered Indexer(mw.some_indexer_3)
2023-10-14T12:00:21.070827Z  INFO fuel_indexer::executor: 106: Indexer(mw.some_indexer_3) subscribing to Fuel node at beta-4.fuel.network:80
2023-10-14T12:00:21.071971Z  WARN fuel_indexer::executor: 115: No end_block specified in the manifest. Indexer(mw.some_indexer_3) will run forever.
2023-10-14T12:00:21.226894Z  INFO fuel_indexer::service: 405: Resuming Indexer(fuellabs.hello_world) from block 93701
2023-10-14T12:00:25.338110Z  INFO fuel_indexer::database: 219: Database loading schema for Indexer(fuellabs.hello_world) with Version(780caa2e6464415ff2f96bfc600e6ff4887f206c07d47771ce8646e668aa5c27).
2023-10-14T12:00:25.340142Z  INFO fuel_indexer::service: 205: Registered Indexer(fuellabs.hello_world)
2023-10-14T12:00:25.340172Z  INFO fuel_indexer::executor: 106: Indexer(fuellabs.hello_world) subscribing to Fuel node at beta-4.fuel.network:80
2023-10-14T12:00:25.340284Z  WARN fuel_indexer::executor: 115: No end_block specified in the manifest. Indexer(fuellabs.hello_world) will run forever.
2023-10-14T12:00:25.430232Z  INFO fuel_indexer::service: 405: Resuming Indexer(fuellabs.explorer) from block 105381
2023-10-14T12:00:30.100731Z  INFO fuel_indexer::database: 219: Database loading schema for Indexer(fuellabs.explorer) with Version(bca69dba935a24f511cef34298b2e1e6e8637c29244b208458c3b73ca6088be3).
2023-10-14T12:00:30.106649Z  INFO fuel_indexer::service: 205: Registered Indexer(fuellabs.explorer)
2023-10-14T12:00:30.106679Z  INFO fuel_indexer::executor: 106: Indexer(fuellabs.explorer) subscribing to Fuel node at beta-4.fuel.network:80
2023-10-14T12:00:30.106777Z  WARN fuel_indexer::executor: 115: No end_block specified in the manifest. Indexer(fuellabs.explorer) will run forever.
2023-10-14T12:00:30.107654Z  INFO fuel_indexer_lib::utils: 144: Parsed SocketAddr '127.0.0.1:29987' from 'localhost:29987'
```

**Comment by ra0x3** [comment] 2023-10-16 14:34
@lostman 
- I see what you're referring to and I believe this is intentional - so I don't think it's a bug
- Keep in mind that `--manifest` for `fuel-indexer` is a debug/local-development flag
- We don't expect anyone to ever really use the `--manifest` flag for `fuel-indexer` unless they're debugging something
  - We use it often because we're often debugging things

**Comment by lostman** [comment] 2023-10-16 16:19
@ra0x3, I see. I use it often when working on the `fuel-indexer`, usually with a single indexer. However, I've been working with multiple indexers recently and was confused about what was happening. I spent some time checking whether I'd broken something in my branch before realizing the behavior was already there.

**Comment by ra0x3** [comment] 2023-10-30 18:17
Gonna close this (because it's not a bug). But @lostman if you want to change/update any functionality related to `--manifest` (understanding that it's a debug option), just open another issue for the work 👌🏼

**Closed as completed by ra0x3** 2023-10-30 18:17 UTC
Labels: bug
