### ISSUE TITLE
Add other event types for indexing.

### ISSUE THREAD

**Issue by tjsharp1** [FuelLabs/fuel-indexer#21] opened 2022-05-13 00:55 UTC
Currently, the indexer only supports the log event type.
We will need to support indexing on the remaining LogReceipt types as well.

**Comment by ra0x3** [comment] 2022-05-25 20:15
Possible dupe of https://github.com/FuelLabs/fuel-indexer/issues/35

**Comment by ra0x3** [comment] 2022-06-29 23:19
Relevant https://github.com/FuelLabs/fuels-rs/pull/431#pullrequestreview-1024105343

**Comment by ra0x3** [comment] 2022-06-30 02:36
@tjsharp1 
- I see what you're saying here. 
- I agree we should maybe focus on 1 or 2 higher priority receipts _then_ introduce everything else
- I think my answer to this is, we should discuss it with the larger group during that call (as you mentioned on Slack)
- Seems like a discussion a lot of people will have opinions on, and making sure everyone is on the same page might be best
- I could personally go for a few different directions

**Closed** 2022-10-30 19:19 UTC
